"""
Core type system for Drone API.

Provides type-safe enums, Pydantic models, and custom exceptions.
"""

from .types import (
    Direction,
    Rotation,
    FlipDirection,
    LEDMode,
    DroneStatus,
    CommandResult,
    VisionMode,
    AIRecognitionTarget,
    CameraMode,
    ClampMode,
    ElectromagnetMode,
    LineFollowResult,
    LineColor,
    LaserMode,
    CameraPitchMode,
    VideoStreamMode,
    QRLocalizationMode,
    MediaType,
    VelocityLevel,
    BarrierMask,
    VideoResolution,
    WiFiMode,
    TakeoffFlags,
)
from .models import (
    Vector3,
    Orientation,
    LEDConfig,
    LEDColor,
    FlightData,
    Obstacles,
    DroneState,
    AIResult,
    ColorResult,
    MediaFile,
)
from .exceptions import (
    DroneError,
    DroneConnectionError,
    CommandTimeout,
    CommandRejected,
    NotReady,
    LowBattery,
    TelemetryUnavailable,
)

__all__ = [
    # Types/Enums
    "Direction",
    "Rotation",
    "FlipDirection",
    "LEDMode",
    "DroneStatus",
    "CommandResult",
    "VisionMode",
    "AIRecognitionTarget",
    "CameraMode",
    "ClampMode",
    "ElectromagnetMode",
    "LineFollowResult",
    "LineColor",
    "LaserMode",
    "CameraPitchMode",
    "VideoStreamMode",
    "QRLocalizationMode",
    "MediaType",
    "VelocityLevel",
    "BarrierMask",
    "VideoResolution",
    "WiFiMode",
    "TakeoffFlags",
    # Models
    "Vector3",
    "Orientation",
    "LEDConfig",
    "LEDColor",
    "FlightData",
    "Obstacles",
    "DroneState",
    "AIResult",
    "ColorResult",
    "MediaFile",
    # Exceptions
    "DroneError",
    "DroneConnectionError",
    "CommandTimeout",
    "CommandRejected",
    "NotReady",
    "LowBattery",
    "TelemetryUnavailable",
]
